---
- name: Configurar Servidor de Base de Datos
  hosts: db
  user: root
  become: true

  roles:
    - db

- name: Configurar Servidor de Aplicación
  hosts: app
  user: root
  become: true

  roles:
    - app
