---
- name: Instalar Apache
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Instalar PHP y extensión MariaDB
  ansible.builtin.dnf:
    name:
      - php
      - php-mysqlnd
    state: present

- name: Instalar Git
  ansible.builtin.dnf:
    name: git
    state: present

- name: Clonar aplicación desde GitHub
  ansible.builtin.git:
    repo: "https://github.com/emverdes/dbappphp.git"
    dest: /var/www/html/dbappphp
    version: HEAD

- name: Copiar template cumple.php
  ansible.builtin.template:
    src: cumple.php.j2
    dest: /var/www/html/dbappphp/cumple.php
    mode: '0644'

- name: Ajustar permisos en /var/www/html
  ansible.builtin.file:
    path: /var/www/html/dbappphp
    owner: luca
    group: luca
    recurse: yes

- name: Habilitar y arrancar Apache
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: Permitir tráfico HTTP en firewalld
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Comprobar acceso HTTP
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}/dbappphp/cumple.php"
    return_content: true
  register: http_result

- name: Validar respuesta de la aplicación
  ansible.builtin.assert:
    that:
      - "'Cumpleaños' in http_result.content"

...
