---
  - name: Instalar Paquetes (MariaDB, Python, UFW, Git)
    ansible.builtin.apt:
      name:
        - mariadb-server
        - python3-pymysql
        - ufw
        - git
      state: present
      update_cache: true

  - name: Mapear el servidor de aplicaciones en /etc/hosts de la DB
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: ".*appsrv$"
      line: "192.168.1.20 appsrv"
      state: present

  - name: Clonar aplicación desde GitHub en /tmp/dbappphp
    ansible.builtin.git:
      repo: "https://github.com/emverdes/dbappphp.git"
      dest: /tmp/dbappphp
      version: main
      force: yes

  - name: Habilitar y arrancar MariaDB
    ansible.builtin.service:
      name: mariadb
      enabled: true
      state: started

  - name: Configurar root para usar mysql_native_password
    ansible.mysql.mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      host: localhost
      plugin: mysql_native_password
      state: present
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Configurar /root/.my.cnf para MariaDB
    ansible.builtin.copy:
      dest: /root/.my.cnf
      content: |
        [client]
        user=root
        password={{ mysql_root_password }}
      owner: root
      group: root
      mode: '0600'

  - name: Creacion de directorio respaldo db
    ansible.builtin.file:
      path: /tmp/db
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Copia de cumpleanios.sql Funcional
    ansible.builtin.copy:
      src: /tmp/dbappphp/cumpleanios.sql
      dest: /tmp/db/cumpleanios.sql
      mode: '0600'
      remote_src: true

  - name: Fix a SQL
    ansible.builtin.lineinfile:
      path: /tmp/db/cumpleanios.sql
      regexp: "^DROP DATABASE"
      line: "DROP DATABASE IF EXISTS cumples;"

  - name: Verificar si la base de datos ya existe
    ansible.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "localhost"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    register: db_check

  - name: Importar base de datos
    ansible.mysql.mysql_db:
      name: "{{ db_name }}"
      state: import
      target: /tmp/db/cumpleanios.sql
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "localhost"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    when: db_name not in db_check.databases


  - name: Crear usuario de aplicación
    ansible.mysql.mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: "{{ db_name }}.*:SELECT"
      host: "192.168.1.20"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "localhost"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Configurar MariaDB para red local
    ansible.builtin.lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: 'bind-address = 192.168.1.11'
    notify: restart mariadb

  - name: Deshabilitar resolución DNS inversa en MariaDB
    ansible.builtin.lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^#?skip-name-resolve'
      line: 'skip-name-resolve'
      insertafter: '\[mysqld\]'
    notify: restart mariadb


  - name: Permitir MariaDB desde servidor de aplicación
    community.general.ufw:
      rule: allow
      proto: tcp
      src: "{{ hostvars['appsrv'].ansible_host }}"
      port: "3306"

  - name: Permitir conexiones SSH en UFW desde el controlador
    community.general.ufw:
      rule: allow
      proto: tcp
      src: "{{ controller_ip }}"
      port: "22"

  - name: Habilitar UFW
    community.general.ufw:
      state: enabled

  - name: CHECK - Validar que MariaDB responda localmente
    ansible.mysql.mysql_ping:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    register: mariadb_ping
    changed_when: false

  - name: CHECK - Verificar que el usuario de la app tenga acceso a la BD
    ansible.mysql.mysql_info:
      filter: databases
      login_user: "{{ db_user }}"
      login_password: "{{ db_password }}"
      login_host: "localhost"
    register: user_db_check
    failed_when: db_name not in user_db_check.databases.keys()
    changed_when: false

  - name: CHECK - Confirmar estado de la Base de Datos
    ansible.builtin.debug:
      msg: "¡Éxito! El usuario '{{ db_user }}' se autentica correctamente y visualiza la base de datos '{{ db_name }}'."

...
